/**************************
***** Compiler Parameters *****
***************************
@P EffectName: SpritePicking
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id72 => SpriteBase.MatrixTransform
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    SpritePicking => 9fa9c13876dcc6e128bb51e67759d4f7
@S    SpriteBase => a411b8f5112d9bc821268e8c81e1a94c
@S    ShaderBase => 5c3160ccbf936c5e102bd9315f0f946a
@S    ShaderBaseStream => f699080594ac63c1f38140de57ce1a7b
@S    Texturing => a9d9ee1fb9a68af7ce6b12291686faea
***************************
*****     Stages      *****
***************************
@G    Vertex => bec218ff0d55f2f1433044c4e055ff66
//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id72;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// PerDraw                           cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyzw        2     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_input v2.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.Position_id71.x; v0.y <- __input__.Position_id71.y; v0.z <- __input__.Position_id71.z; v0.w <- __input__.Position_id71.w; 
//   v1.x <- __input__.TexCoord_id61.x; v1.y <- __input__.TexCoord_id61.y; 
//   v2.x <- __input__.Color_id73.x; v2.y <- __input__.Color_id73.y; v2.z <- __input__.Color_id73.z; v2.w <- __input__.Color_id73.w; 
//   o2.x <- <VSMain return value>.Color_id73.x; o2.y <- <VSMain return value>.Color_id73.y; o2.z <- <VSMain return value>.Color_id73.z; o2.w <- <VSMain return value>.Color_id73.w; 
//   o1.x <- <VSMain return value>.TexCoord_id61.x; o1.y <- <VSMain return value>.TexCoord_id61.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 82 "C:\Development\three-dee\1 - Code\ThreeDeeCore\CoreFacade\log\shader_SpritePicking_50b1e644249ea8f25fdc62c2e60f200d.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 87
mov o1.xy, v1.xyxx
mov o2.xyzw, v2.xyzw
ret 
// Approximately 7 instruction slots used
@G    Pixel => 284be55958426c1f565162804e1dab36
//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float       
// COLOR                    0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id61.x; v1.y <- __input__.TexCoord_id61.y; 
//   v2.x <- __input__.Color_id73.x; v2.y <- __input__.Color_id73.y; v2.z <- __input__.Color_id73.z; v2.w <- __input__.Color_id73.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id1.x; o0.y <- <PSMain return value>.ColorTarget_id1.y; o0.z <- <PSMain return value>.ColorTarget_id1.z; o0.w <- <PSMain return value>.ColorTarget_id1.w
//
#line 59 "C:\Development\three-dee\1 - Code\ThreeDeeCore\CoreFacade\log\shader_SpritePicking_50b1e644249ea8f25fdc62c2e60f200d.hlsl"
mul r0.xyzw, v2.wxyz, l(255.000000, 255.000000, 255.000000, 255.000000)
ftoi r0.xyzw, r0.xyzw

#line 62
bfi r0.zw, l(0, 0, 8, 8), l(0, 0, 8, 16), r0.zzzw, l(0, 0, 0, 0)
bfi r0.y, l(8), l(0), r0.y, r0.z  // r0.y <- value
iadd r0.y, r0.w, r0.y
bfi r0.x, l(8), l(24), r0.x, r0.y  // r0.x <- value
itof o0.x, r0.x
mov o0.yzw, l(0,0,0,1.000000)

#line 74
ret 
// Approximately 9 instruction slots used
***************************
*************************/
Texture2D Texture0_id13;
SamplerState Sampler_id41;
struct PS_STREAMS 
{
    float2 TexCoord_id61;
    float4 Color_id73;
    float4 ColorTarget_id1;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id1 : SV_Target0;
};
struct VS_STREAMS 
{
    float4 Position_id71;
    float2 TexCoord_id61;
    float4 Color_id73;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id61 : TEXCOORD0;
    float4 Color_id73 : COLOR;
};
struct VS_INPUT 
{
    float4 Position_id71 : POSITION;
    float2 TexCoord_id61 : TEXCOORD0;
    float4 Color_id73 : COLOR;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id72;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id14;
    float2 Texture1TexelSize_id16;
    float2 Texture2TexelSize_id18;
    float2 Texture3TexelSize_id20;
    float2 Texture4TexelSize_id22;
    float2 Texture5TexelSize_id24;
    float2 Texture6TexelSize_id26;
    float2 Texture7TexelSize_id28;
    float2 Texture8TexelSize_id30;
    float2 Texture9TexelSize_id32;
};
float4 Shading_id2(inout PS_STREAMS streams)
{
    return Texture0_id13.Sample(Sampler_id41, streams.TexCoord_id61);
}
float4 Shading_id3(inout PS_STREAMS streams)
{
    Shading_id2(streams);
    int a = (int)(streams.Color_id73.a * 255.0f) & 255;
    int r = (int)(streams.Color_id73.r * 255.0f) & 255;
    int g = (int)(streams.Color_id73.g * 255.0f) & 255;
    int b = (int)(streams.Color_id73.b * 255.0f) & 255;
    int value = r;
    value |= g << 8;
    value |= b << 16;
    value |= a << 24;
    return float4(value, 0, 0, 1);
}
PS_OUTPUT PSMain(VS_OUTPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id61 = __input__.TexCoord_id61;
    streams.Color_id73 = __input__.Color_id73;
    streams.ColorTarget_id1 = Shading_id3(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id1 = streams.ColorTarget_id1;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id71 = __input__.Position_id71;
    streams.TexCoord_id61 = __input__.TexCoord_id61;
    streams.Color_id73 = __input__.Color_id73;
    streams.ShadingPosition_id0 = mul(streams.Position_id71, MatrixTransform_id72);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id61 = streams.TexCoord_id61;
    __output__.Color_id73 = streams.Color_id73;
    return __output__;
}
